# Generated by Django 4.0 on 2021-12-25 16:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cda650d6-3ad5-4284-98b9-0b063fea7b92'), primary_key=True, serialize=False),
        ),
    ]
